spring.application.name=usagetranslator


usagetranslator.skipPartnerIds=26392

usagetranslator.unitReduction.EA000001GB0O=1000
usagetranslator.unitReduction.PMQ00005GB0R=5000
usagetranslator.unitReduction.SSX006NR=1000
usagetranslator.unitReduction.SPQ00001MB0R=2000